export const BrandURL =  'http://localhost:3001/api/brands';

export const urlMap = {
    "Cocacola" : "https://vignette.wikia.nocookie.net/logopedia/images/5/59/Coca-Cola_logo_2007.jpg/revision/latest?cb=20150801090518",
    "Adidas": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Adidas_Logo.svg/2000px-Adidas_Logo.svg.png",
    "Apple": "https://3.bp.blogspot.com/-Xq3PfhewPlk/WQ7DUs_xpgI/AAAAAAAAAqQ/aDVfzyfm000XWUx4gSm36f21DCGemh2gQCLcB/s1600/Apple%2BMac.png",
    "BMW": "https://seeklogo.com/images/B/bmw-logo-F4A92B9BC1-seeklogo.com.png",
    "Citroen": "http://www.car-brand-names.com/wp-content/uploads/2015/10/Citroen-Logo.png",
    "DHL": "http://findwarehousejobs.com/wp-content/uploads/2016/01/dhl-logo.jpg",
    "Fedex":"http://static.neatorama.com/images/2012-09/fedex-logo.jpg",
    "Ferrari":"https://ih0.redbubble.net/image.482871518.5073/ap,550x550,16x12,1,transparent,t.png",
    "Ford": "http://www.car-brand-names.com/wp-content/uploads/2015/07/Ford-logo.jpg",
    "Google": "https://storage.googleapis.com/gd-wagtail-prod-assets/original_images/evolving_google_identity_videoposter_006.jpg",
    "HP": "https://vignette.wikia.nocookie.net/logopedia/images/1/18/Hp-1.jpg/revision/latest/scale-to-width-down/262?cb=20160810214851",
    "Heineken": "https://seeklogo.com/images/H/heineken-logo-C4F7E290E9-seeklogo.com.png",
    "Intel": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPYA09UuJhocgbo_e1X4v7eXLna_Lezb9CF_VPEuymJiZe1Smb",
    "McDonalds": "http://pngimg.com/uploads/mcdonalds/mcdonalds_PNG17.png",
    "Mini": "http://www.carlogos.org/logo/Mini-logo-2001-1920x1080.png",
    "Nbc": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/NBC_logo.svg/2000px-NBC_logo.svg.png",
    "Nike": "https://seeklogo.com/images/N/nike-logo-47A65A59D5-seeklogo.com.png",
    "Pepsi": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjBW9oEhS1CX81_PYKqse1BMaZ7rILD-HmpFQ-6uVvCzNVhF-tCw",
    "Porsche": "https://images.fineartamerica.com/images/artworkimages/mediumlarge/1/4-porsche-logo-porsche-logo.jpg",
    "Puma": "https://seeklogo.com/images/P/puma-logo-F9E13B654C-seeklogo.com.png",
    "RedBull": "http://graphicmore.com/wp-content/uploads/2016/05/Red-Bull-Logo-Design-Free-Vector-File.jpg",
    "Sprite": "https://seeklogo.com/images/S/sprite-logo-1C8CE6BD76-seeklogo.com.png",
    "Starbucks": "https://www.delpoplumbinghvac.com/wp-content/uploads/2015/11/starbucks-logo.png",
    "Texaco": "https://seeklogo.com/images/T/Texaco-logo-71FE11DF94-seeklogo.com.png",
    "Unicef": "http://1000logos.net/wp-content/uploads/2017/06/UNICEF-Logo.jpg",
    "Vodafone": "https://seeklogo.com/images/V/vodafone-logo-7CCAEF2C51-seeklogo.com.png",
    "Yahoo": "https://logos-download.com/wp-content/uploads/2016/02/Yahoo_Logo_big.png"
}